name: docs

on:
  push:
    branches:
      - gcam-v6.0

jobs:
  pkgdown:
    runs-on: ubuntu-latest
    
    env:
      R_REMOTES_NO_ERRORS_FROM_WARNINGS: true
      GITHUB_PAT: ${{ secrets.GH_GCAMREPORT_TOKEN}}
      RSPM: ${{ matrix.config.rspm }}

    steps:
      - uses: actions/checkout@v2

      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: '4.1.0'

      - uses: r-lib/actions/setup-pandoc@v2

      - name: Install libcurl
        run: |
          sudo apt-get update
          sudo apt-get install -y libcurl4-openssl-dev
      
      - name: Restart R
        run: |
          R --vanilla --quiet
          echo 'q()' | R --no-save

      - name: Install dependencies 1
        run: |
          install.packages(c("remotes", "rcmdcheck"), repos = "https://cloud.r-project.org")
        shell: Rscript {0}

      # - name: Set default repository
      #   run: |
      #     options(repos = c(CRAN = "https://cran.rstudio.com/"))
      #   shell: Rscript {0}

      ## FIX 16
      - name: Install dependencies 2
        run: |
          remotes::install_deps(dependencies = TRUE)
        shell: Rscript {0}

      # ## FIX 15
      # - name: Install dependencies 2
      #   run: |
      #     install.packages(c("markdown", "readr", "Rcpp", "gtable", "data.table", "gridExtra", "pkgdown", "devtools", "dplyr", "tidyr", "rgcam", "ggplot2", "here", "extrafont", "RColorBrewer", "shiny", "shinyTree", "shinyWidgets", "shinydashboard", "shinyjs", "rrapply"), repos = "https://cloud.r-project.org", dependecies = TRUE)
      #   shell: Rscript {0}

      # - name: Install dependencies 2.5
      #   run: |
      #     devtools::install_github('JorisChau/rrapply')
      #   shell: Rscript {0}


      - name: Install dependencies 3
        run: |
          install.packages("pkgdown")
        shell: Rscript {0}

      - name: Install package
        run: R CMD INSTALL .

      - name: Deploy package
        run: |
          git config --local user.name "$GITHUB_ACTOR"
          git config --local user.email "$GITHUB_ACTOR@users.noreply.github.com"
          Rscript -e 'pkgdown::deploy_to_branch(new_process = FALSE)'